services:
  db:
    container_name: mongodb
    image: mongo:4.4
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - dbdata:/data/db
    networks:
      sbi:
        aliases:
          - db.free5gc.org

  amf:
    container_name: amf
    image: free5gc/amf:latest
    command: ./amf -c ./config/amfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/amfcfg.yaml:/free5gc/config/amfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      sbi:
        aliases:
          - amf.free5gc.org
      cn-ran:
        ipv4_address: 10.0.1.3
        aliases:
          - n2.free5gc.org
    depends_on:
      - nrf

  ausf:
    container_name: ausf
    image: free5gc/ausf:latest
    command: ./ausf -c ./config/ausfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/ausfcfg.yaml:/free5gc/config/ausfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      sbi:
        aliases:
          - ausf.free5gc.org
    depends_on:
      - nrf

  chf:
    container_name: chf
    image: free5gc/chf:latest
    command: ./chf -c ./config/chfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/chfcfg.yaml:/free5gc/config/chfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      sbi:
        aliases:
          - chf.free5gc.org
    depends_on:
      - db
      - nrf
      - webconsole

  nrf:
    container_name: nrf
    image: free5gc/nrf:latest
    command: ./nrf -c ./config/nrfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nrfcfg.yaml:/free5gc/config/nrfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      sbi:
        aliases:
          - nrf.free5gc.org
    depends_on:
      - db

  nssf:
    container_name: nssf
    image: free5gc/nssf:latest
    command: ./nssf -c ./config/nssfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nssfcfg.yaml:/free5gc/config/nssfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      sbi:
        aliases:
          - nssf.free5gc.org
    depends_on:
      - nrf

  pcf:
    container_name: pcf
    image: free5gc/pcf:latest
    command: ./pcf -c ./config/pcfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/pcfcfg.yaml:/free5gc/config/pcfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      sbi:
        aliases:
          - pcf.free5gc.org
    depends_on:
      - nrf

  smf:
    container_name: smf
    build:
      context: ./nf_smf
      args:
        DEBUG_TOOLS: "false"
    command: ./smf -c ./config/smfcfg.yaml -u ./config/uerouting.yaml
    expose:
      - "8000"
    volumes:
      - ./config/ULCL/smfcfg.yaml:/free5gc/config/smfcfg.yaml
      - ./config/ULCL/uerouting.yaml:/free5gc/config/uerouting.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      sbi:
        aliases:
          - smf.free5gc.org
    depends_on:
      - nrf
      - i-upf-1
      - psa-upf-1

  udm:
    container_name: udm
    image: free5gc/udm:latest
    command: ./udm -c ./config/udmcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udmcfg.yaml:/free5gc/config/udmcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      sbi:
        aliases:
          - udm.free5gc.org
    depends_on:
      - db
      - nrf

  udr:
    container_name: udr
    image: free5gc/udr:latest
    command: ./udr -c ./config/udrcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udrcfg.yaml:/free5gc/config/udrcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      sbi:
        aliases:
          - udr.free5gc.org
    depends_on:
      - db
      - nrf

  i-upf-1:
    container_name: i-upf-1
    build:
      context: ./nf_upf
      args:
        DEBUG_TOOLS: "false"
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/ULCL/i-upfcfg-1.yaml:/free5gc/config/upfcfg.yaml
      - ./script/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      sbi:
        aliases:
          - i-upf-1.free5gc.org
      cn-ran:
        ipv4_address: 10.0.1.5
        aliases:
          - n3-1.free5gc.org

  i-upf-2:
    container_name: i-upf-2
    build:
      context: ./nf_upf
      args:
        DEBUG_TOOLS: "false"
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/ULCL/i-upfcfg-2.yaml:/free5gc/config/upfcfg.yaml
      - ./script/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      sbi:
        aliases:
          - i-upf-2.free5gc.org
      cn-ran:
        ipv4_address: 10.0.1.9
        aliases:
          - n3-2.free5gc.org

  psa-upf-1:
    container_name: psa-upf-1
    build:
      context: ./nf_upf
      args:
        DEBUG_TOOLS: "false"
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/ULCL/psa-upfcfg-1.yaml:/free5gc/config/upfcfg.yaml
      - ./script/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      sbi:
        aliases:
          - psa-upf-1.free5gc.org
      cn-ran:
        ipv4_address: 10.0.1.7
        aliases:
          - n9-1.free5gc.org

  psa-upf-2:
    container_name: psa-upf-2
    build:
      context: ./nf_upf
      args:
        DEBUG_TOOLS: "false"
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/ULCL/psa-upfcfg-2.yaml:/free5gc/config/upfcfg.yaml
      - ./script/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      sbi:
        aliases:
          - psa-upf-2.free5gc.org
      cn-ran:
        ipv4_address: 10.0.1.11
        aliases:
          - n9-2.free5gc.org

  webconsole:
    container_name: webconsole
    image: free5gc/webui:latest
    command: ./webui -c ./config/webconsolecfg.yaml
    expose:
      - "2121"
    volumes:
      - ./config/free5gc-consolecfg.yaml:/free5gc/config/webconsolecfg.yaml
    environment:
      - GIN_MODE=release
    networks:
      sbi:
        aliases:
          - webconsole
    ports:
      - "5000:5000"
      - "2122:2122"
      - "2121:2121"
    depends_on:
      - db
      - nrf

  gnb-1:
    container_name: gnb-1
    image: free-ran-ue:latest
    command: ./free-ran-ue gnb -c ./gnbcfg.yaml
    volumes:
      - ./config/gnbcfg-1.yaml:/free-ran-ue/gnbcfg.yaml
    networks:
      cn-ran:
        ipv4_address: 10.0.1.2
        aliases:
          - gnb-1.free5gc.org
      ran-ue:
        ipv4_address: 10.0.2.3
    depends_on:
      - amf
      - ausf
      - chf
      - nrf
      - nssf
      - pcf
      - smf
      - udm
      - udr
      - i-upf-1
      - psa-upf-1

  gnb-2:
    container_name: gnb-2
    image: free-ran-ue:latest
    command: ./free-ran-ue gnb -c ./gnbcfg.yaml
    volumes:
      - ./config/gnbcfg-2.yaml:/free-ran-ue/gnbcfg.yaml
    networks:
      cn-ran:
        ipv4_address: 10.0.1.4
        aliases:
          - gnb-2.free5gc.org
      ran-ue:
        ipv4_address: 10.0.2.5
    depends_on:
      - amf
      - ausf
      - chf
      - nrf
      - nssf
      - pcf
      - smf
      - udm
      - udr
      - i-upf-2
      - psa-upf-2

  ue-1:
    container_name: ue-1
    image: free-ran-ue:latest
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./config/uecfg-1.yaml:/free-ran-ue/uecfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      ran-ue:
        ipv4_address: 10.0.2.2
    depends_on:
      - gnb-1

  ue-2:
    container_name: ue-2
    image: free-ran-ue:latest
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./config/uecfg-2.yaml:/free-ran-ue/uecfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      ran-ue:
        ipv4_address: 10.0.2.4
    depends_on:
      - gnb-2

networks:
  sbi:
    ipam:
      driver: default
      config:
        - subnet: 10.0.10.0/24
    driver_opts:
      com.docker.network.bridge.name: docker-sbi

  cn-ran:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
    driver_opts:
      com.docker.network.bridge.name: docker-cn-ran

  ran-ue:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
    driver_opts:
      com.docker.network.bridge.name: docker-ran-ue

volumes:
  dbdata:
