name: Docker Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          make docker

      - name: Test Docker image
        run: |
          docker images
          docker run --rm free-ran-ue:latest ls /free-ran-ue/free-ran-ue
          docker run --rm free-ran-ue:latest ls /free-ran-ue/console
