name: Integration Test

on:
  workflow_dispatch:
  issue_comment:
    types: [created]
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  integration-test:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        startsWith(github.event.comment.body, 'run-integration-test') &&
        github.actor == 'Alonza0314'
      )
    runs-on: self-hosted

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Check commands
        run: |
          docker --version
          curl --version
          jq --version

      - name: Build free-ran-ue image
        run: make docker

      - name: Test free-ran-ue image
        run: |
          docker images
          docker run --rm free-ran-ue:latest ls /free-ran-ue/free-ran-ue
          docker run --rm free-ran-ue:latest ls /free-ran-ue/console

      - name: Run test basic
        run: ./script/integration-test-script/integration-test.sh basic

      - name: Run test dc-static
        run: ./script/integration-test-script/integration-test.sh dc-static

      - name: Run test dc-dynamic
        run: ./script/integration-test-script/integration-test.sh dc-dynamic

      - name: Run test ulcl
        run: ./script/integration-test-script/integration-test.sh ulcl

      - name: Clean up docker resources
        if: always()
        run: docker system prune -a -f --volumes
